# Generated by Django 2.2.2 on 2020-01-25 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employement',
            new_name='employment',
        ),
    ]
